language: generic
sudo:     false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - env: IC_PYTHON_VERSION=3.7

git:
  lfs_skip_smudge: true

env:
  - IC_PYTHON_VERSION=3.7
  - IC_PYTHON_VERSION=3.6

os:
  - linux
  - osx

branches:
  except:
    - /^docs\..*$/

before_install:
  - GIT_SSL_NO_VERIFY=1 git lfs pull

install:
  - source manage.sh work_in_python_version_no_tests ${IC_PYTHON_VERSION}

script:
  - HYPOTHESIS_PROFILE=hard bash manage.sh run_tests_par 4
